name: Release Tag

on:
  push:
    tags:
      - v*.*.*
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@c1e51972afc2121e065aed6d45c65596fe445f3f
        id: meta
        with:
          images: ${{ github.repository }}

      - uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          file: ./Dockerfile
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
